---
- hosts: music
  become: yes
  vars:
          ssh_users: 'Lab_Trolls'
          prov_group: 'music'
          ssh_folder: '/home/{{ item.name }}/.ssh'
          ssh_key_path: '{{ ssh_folder }}/authorized_keys'
  pre_tasks:
          - name: updating users.yml file
            local_action: command ./pullRSA.py '{{ ssh_users }}'
  tasks:
          - name: adding users
            include_vars:
                    file: users.yml
          - name: creating shared group
            group:
                    name: '{{ prov_group }}'
          - name: creating users groups
            group:
                    name: '{{ item.name }}'
            loop: '{{ users }}'
          - name: creating users
            user:
                    name: '{{ item.name }}'
                    groups: '{{ item.name }},{{ prov_group }}'
            loop: '{{ users }}'
          - name: creating .ssh folder
            file:
                    path: '{{ ssh_folder }}'
                    owner: '{{ item.name }}'
                    group: '{{ item.name }}'
                    state: directory
            loop: '{{ users }}'
          - name: creating all authorized_keys files
            file:
                    path: '{{ ssh_key_path }}'
                    owner: '{{ item.name }}'
                    group: '{{ item.name }}'
                    mode: 0600
                    state: touch
            loop: '{{ users }}'
          - name: adding rsa keys
            lineinfile:
                    path: '{{ ssh_key_path }}'
                    owner: '{{ item.name }}'
                    group: '{{ item.name }}'
                    line: '{{ item.rsaKey }}'
            loop: '{{ users }}'
...
